config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "lists#index"
  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
    validates :content , presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     add_flash_types :success, :info, :warning, :danger
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
     @lists = List.all
    end
    
    def show
        @list = List.find(params[:id])
    end
    
    def new
        @list = List.new
    end
    
    def create
        @list = List.new(list_params)
        if @list.save
            redirect_to @list
        else
            render 'new', status: :unprocessable_entity
        end
        
    end
    
    def edit
        @list = List.find(params[:id])
    end
    
    def update
        @list = List.find(params[:id])
        if @list.update(list_params)
            redirect_to @list, success: "update success"
        else
           render 'end', status: :unprocessable_entity
        end
    end
    
    def destroy
        @list = List.find(params[:id])
        @list.destroy
        redirect_to lists_path
    end
    
    private
    def list_params
        params.require(:list).permit(:content,:compeleted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_flash.html.erb
<% flash.each do |key, value| %>
   <p class="alert alert-<%= key %>">
     <%= value %>
   </p>
<% end %>

app/views/lists/edit.html.erb
<h1>edit</h1>
<%= form_with model:@list do |form| %>
    <% if @list.errors.any? %>
        <div>
            <ul>
                <% @list.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div>
        <%= form.label :content %><br>
        <%= form.text_field :content %>
    </div>
    
    <div>
        <%= form.label :compeleted %><br>
        <%= form.check_box :compeleted, {}, "finished", "false"  %>
    </div><br>
    
    <div>
        <%= form.submit :class => "btn btn-primary"%>
    </div>
<% end %>
    <br>
<%= link_to 'top', lists_path, :class => "btn btn-outline-dark" %>

app/views/lists/index.html.erb
<br>
<div class="container d-flex justify-content-between">
    <h1>lists</h1>
    <div><%= link_to 'add new item', new_list_path , :class => "btn btn-primary btn-lg"%></div>
</div>

<table class="table table-primary" style="width: 80%">
    <tr>
        <th>ID</th>
        <th>Content</th>
        <th>Check</th>
    </tr>
    <% @lists.each do |list| %>
        <% if list.compeleted %>
            <tr>
                <td><%= list.id %></td>
                <td class="striker fs-5"><%= link_to list.content, edit_list_path(list)%></td>
                <td class="fs-5"><p>finished</p></td>
                <td><%= link_to 'show', list_path(list), :class =>"btn btn-outline-dark btn-lg px-5", :style => "width:200px" %>
                    <%= link_to 'edit', edit_list_path(list), :class =>"btn btn-outline-dark btn-lg px-5", :style => "width:200px"%>
                    <%= link_to 'destroy', list_path(list), :class =>"btn btn-outline-dark btn-lg px-5",:style => "width:200px",
                    data: { turbo_method: 'delete', turbo_confirm: 'Are you sure? '}%>
                </td>
            </tr>
        <% else %>
            <tr class="table-light">
                <td><%= list.id %></td>
                <td class="fs-5"><%= link_to list.content, edit_list_path(list) %></td>
                <td class="fs-5"><p>in progress...</p></td>
                <td><%= link_to 'show', list_path(list), :class =>"btn btn-outline-dark btn-lg px-5", :style => "width:200px" %>
                <%= link_to 'edit', edit_list_path(list), :class =>"btn btn-outline-dark btn-lg px-5", :style => "width:200px" %>
                <%= link_to 'destroy', list_path(list), :class =>"btn btn-outline-dark btn-lg px-5", :style => "width:200px",
                    data: { turbo_method: 'delete', turbo_confirm: 'are you serious? マジで？'}%>
                </td>
            </tr>
        <% end %>
    <% end %>
    
</table>

app/views/lists/new.html.erb
<h1>New lists</h1>
<%= form_with model:@list do |form| %>
    <% if @list.errors.any? %>
        <div>
            <ul>
                <% @list.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div>
        <%= form.label :content %><br>
        <%= form.text_field :content %>
    </div>
    
    <div>
        <%= form.label :compeleted %><br>
        <%= form.check_box :compeleted, {}, "finished", "false"  %>
    </div><br>
    
    <div>
        <%= form.submit :class => "btn btn-primary"%>
    </div>
<% end %>

<br><%= link_to 'top', lists_path, :class => "btn btn-outline-dark" %>

app/views/lists/show.html.erb
<%=  flash[:success] %>
<h1>Show</h1>

<table  class="table table-primary" style= "width: 300px">
    
    <tr>
        <th>Content:</th>
        <th><p>・<%= @list.content %></p></th>
        
    </tr>
    <tr>
        <th>Completed:</th>
        <% if @list.compeleted %>
            <th><p>・finished</p></th>
        <% else %>
            <th><p>・ in progress ...</p></th>
        <% end %>
    </tr>
</table>

<%= link_to 'top', lists_path, :class => "btn btn-primary btn-lg"%>